slogo_team12: view.Editor Class Reference
view.Editor Class Reference
Public Member Functions
Editor (Parser parser, SideBar sidebar, Dimension2D dimensions)
Private Member Functions
void parse ()
void createTextEditor (Dimension2D dimensions)
void createRunButton ()
Private Attributes
Button runButton
TextArea textEditor
Parser myParser
SideBar mySidebar
Detailed Description
Lower panel containing the text editor that reads in user text input.
Author
Callie
Definition at line 15 of file Editor.java.
Constructor & Destructor Documentation
view.Editor.Editor (Parser parser, SideBar sidebar, Dimension2D dimensions)
Definition at line 22 of file Editor.java.
References view.Editor.createRunButton(), and view.Editor.createTextEditor().
Member Function Documentation
void view.Editor.createRunButton () private
Definition at line 46 of file Editor.java.
References view.Editor.parse().
Referenced by view.Editor.Editor().
void view.Editor.createTextEditor (Dimension2D dimensions) private
Definition at line 39 of file Editor.java.
Referenced by view.Editor.Editor().
void view.Editor.parse () private
Definition at line 32 of file Editor.java.
References model.Parser.parseAndExecute(), and view.SideBar.setHistory().
Referenced by view.Editor.createRunButton().
Member Data Documentation
Parser view.Editor.myParser private
Definition at line 19 of file Editor.java.
SideBar view.Editor.mySidebar private
Definition at line 20 of file Editor.java.
Button view.Editor.runButton private
Definition at line 17 of file Editor.java.
TextArea view.Editor.textEditor private
Definition at line 18 of file Editor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/Editor.java