slogo_team12: view.ViewUpdater Class Reference
view.ViewUpdater Class Reference
Public Member Functions
ViewUpdater (SLogoView view)
double clearScreen (int id)
void showTurtle (int id, boolean show)
double setXY (int id, double x, double y)
double towards (int id, double x, double y)
double setHeading (int id, double angle, boolean relative)
void setPenUp (int id, boolean setPen)
double getPenDown (int id)
double isShowing (int id)
double getHeading (int id)
double getXCor (int id)
double getYCor (int id)
void update (Observable o, Object arg)
void updateWorkspace (List< TurtleCommand > instructionList)
double setBackgroundColor (double index)
double setPenColor (double index)
double setPenSize (double index)
double setShape (double i, int id)
double getShapeIndex (int id)
double createStamp (int id)
double clearStamps (int id)
Package Attributes
Workspace myWorkspace
SideBar mySidebar
Drawer myDrawer
Private Member Functions
void updateCommand (String s)
Detailed Description
Intermediary class that updates the view from the model
Author
Callie
Definition at line 18 of file ViewUpdater.java.
Constructor & Destructor Documentation
view.ViewUpdater.ViewUpdater (SLogoView view)
Definition at line 24 of file ViewUpdater.java.
References view.SLogoView.getDrawer(), view.SLogoView.getSidebar(), and view.SLogoView.getWorkspace().
Member Function Documentation
double view.ViewUpdater.clearScreen (int id)
Definition at line 30 of file ViewUpdater.java.
References view.Workspace.clearLines(), view.Workspace.getTurtleMap(), and view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
double view.ViewUpdater.clearStamps (int id)
Definition at line 188 of file ViewUpdater.java.
References view.TurtleView.clearStamps(), and view.Workspace.getTurtleMap().
Referenced by model.instructions.FrontEndInstruction.execute().
double view.ViewUpdater.createStamp (int id)
Definition at line 183 of file ViewUpdater.java.
References view.TurtleView.createStamp(), and view.Workspace.getTurtleMap().
Referenced by model.instructions.FrontEndInstruction.execute().
double view.ViewUpdater.getHeading (int id)
Definition at line 85 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.ViewUpdater.getPenDown (int id)
Definition at line 73 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.ViewUpdater.getShapeIndex (int id)
Definition at line 179 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
double view.ViewUpdater.getXCor (int id)
Definition at line 90 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.ViewUpdater.getYCor (int id)
Definition at line 94 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.ViewUpdater.isShowing (int id)
Definition at line 79 of file ViewUpdater.java.
References view.Workspace.getTurtleMap().
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.ViewUpdater.setBackgroundColor (double index)
Definition at line 121 of file ViewUpdater.java.
References view.Workspace.setBackground().
Referenced by model.instructions.FrontEndInstruction.execute().
double view.ViewUpdater.setHeading (int id, double angle, boolean relative)
Definition at line 56 of file ViewUpdater.java.
References view.Workspace.getTurtleMap(), and view.SideBar.updateTurtleProperties().
Referenced by view.ViewUpdater.towards().
double view.ViewUpdater.setPenColor (double index)
Definition at line 138 of file ViewUpdater.java.
References view.Drawer.changeColor().
Referenced by model.instructions.FrontEndInstruction.execute().
double view.ViewUpdater.setPenSize (double index)
Definition at line 155 of file ViewUpdater.java.
References view.Drawer.setStroke().
Referenced by model.instructions.FrontEndInstruction.execute().
void view.ViewUpdater.setPenUp (int id, boolean setPen)
Definition at line 68 of file ViewUpdater.java.
References view.Workspace.getTurtleMap(), and view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
double view.ViewUpdater.setShape (double i, int id)
Definition at line 160 of file ViewUpdater.java.
References view.Workspace.getActiveTurtle(), and view.Workspace.getTurtleMap().
Referenced by model.instructions.FrontEndInstruction.execute().
double view.ViewUpdater.setXY (int id, double x, double y)
Definition at line 43 of file ViewUpdater.java.
References view.Workspace.getTurtleMap(), and view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
void view.ViewUpdater.showTurtle (int id, boolean show)
Definition at line 38 of file ViewUpdater.java.
References view.Workspace.getTurtleMap(), and view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
double view.ViewUpdater.towards (int id, double x, double y)
Definition at line 49 of file ViewUpdater.java.
References view.ViewUpdater.setHeading().
Referenced by model.instructions.MovementInstruction.execute().
void view.ViewUpdater.update (Observable o, Object arg)
Definition at line 104 of file ViewUpdater.java.
References model.ExecutionEnvironment.getUserCommandMap(), model.ExecutionEnvironment.getVariableMap(), view.ViewUpdater.updateCommand(), view.SideBar.updateExecutionEnvironment(), and view.SideBar.updateVariable().
void view.ViewUpdater.updateCommand (String s) private
Definition at line 99 of file ViewUpdater.java.
References view.SideBar.updateCommand().
Referenced by view.ViewUpdater.update().
void view.ViewUpdater.updateWorkspace (List< TurtleCommand > instructionList)
Definition at line 116 of file ViewUpdater.java.
References view.Drawer.draw(), view.Workspace.getLines(), view.Workspace.getTurtleMap(), and view.ViewUpdater.mySidebar.
Referenced by model.instructions.MovementInstruction.updateView().
Member Data Documentation
Drawer view.ViewUpdater.myDrawer package
Definition at line 22 of file ViewUpdater.java.
SideBar view.ViewUpdater.mySidebar package
Definition at line 21 of file ViewUpdater.java.
Referenced by view.ViewUpdater.updateWorkspace().
Workspace view.ViewUpdater.myWorkspace package
Definition at line 20 of file ViewUpdater.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/ViewUpdater.java