slogo_team12: model.TurtleCommand Class Reference
model.TurtleCommand Class Reference
Public Member Functions
TurtleCommand (int turtleId, Polar polar, boolean relative)
void setTurtleId (int turtleId)
void setPolar (Polar polar)
int getTurtleId ()
Polar getPolar ()
boolean isRelative ()
Private Attributes
int myTurtleId
Polar myPolar
boolean myIsRelative
Detailed Description
This very important class holds information about Turtles The getters and setters in this class are called across the program This class allows the model and the view to communicate The model places information into a TurtleCommand and then sends it to the View The view can read the information in TurtleCommands and move the Turtle accordingly This class is primarily used for commands that physically move the Turtle
Authors
Greg, Sid, Mengchao
Definition at line 14 of file TurtleCommand.java.
Constructor & Destructor Documentation
model.TurtleCommand.TurtleCommand (int turtleId, Polar polar, boolean relative)
Definition at line 20 of file TurtleCommand.java.
Member Function Documentation
Polar model.TurtleCommand.getPolar ()
Definition at line 38 of file TurtleCommand.java.
References model.TurtleCommand.myPolar.
Referenced by view.Drawer.draw().
int model.TurtleCommand.getTurtleId ()
Definition at line 34 of file TurtleCommand.java.
References model.TurtleCommand.myTurtleId.
Referenced by view.Drawer.draw().
boolean model.TurtleCommand.isRelative ()
Definition at line 42 of file TurtleCommand.java.
References model.TurtleCommand.myIsRelative.
Referenced by view.Drawer.draw().
void model.TurtleCommand.setPolar (Polar polar)
Definition at line 30 of file TurtleCommand.java.
void model.TurtleCommand.setTurtleId (int turtleId)
Definition at line 26 of file TurtleCommand.java.
Member Data Documentation
boolean model.TurtleCommand.myIsRelative private
Definition at line 18 of file TurtleCommand.java.
Referenced by model.TurtleCommand.isRelative().
Polar model.TurtleCommand.myPolar private
Definition at line 17 of file TurtleCommand.java.
Referenced by model.TurtleCommand.getPolar().
int model.TurtleCommand.myTurtleId private
Definition at line 16 of file TurtleCommand.java.
Referenced by model.TurtleCommand.getTurtleId().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/TurtleCommand.java