slogo_team12: model.ExecutionEnvironment Class Reference
model.ExecutionEnvironment Class Reference
Public Member Functions
ExecutionEnvironment ()
void addCommand (String commandName, Instruction inInstruction)
void addTurtle (double d)
Set< Integer > getTurtles ()
void addVariable (String variableName, Double value)
Double getVariable (String key)
void removeDuplicate (String s)
Instruction getCommand (String key)
void clear ()
int getActiveTurtle ()
void setActiveTurtle (double turtle)
Map< String, Instruction > getUserCommandMap ()
Map< String, Double > getVariableMap ()
Set< Integer > getActiveList ()
void clearActiveList ()
void addTurtleToActiveList (double turtle)
Private Member Functions
void updateObserver ()
Private Attributes
Map< String, Instruction > myUserInstructionMap
Map< String, Double > myVariableMap
Set< Integer > myTurtleList
Set< Integer > activeTurtleList
int activeTurtle
Detailed Description
Execution environment holds user instructions, variables, and a list of turtles This environment is observable and is accessed by the Parser and View By making it observable, there are fewer method calls and public variables Whenever any of the variables is updated, the view will know about it
Author
Greg
Definition at line 20 of file ExecutionEnvironment.java.
Constructor & Destructor Documentation
model.ExecutionEnvironment.ExecutionEnvironment ()
Definition at line 28 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.clear().
Member Function Documentation
void model.ExecutionEnvironment.addCommand (String commandName, Instruction inInstruction)
Definition at line 32 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by model.instructions.ControlInstruction.addToMap(), and model.Parser.makeTree().
void model.ExecutionEnvironment.addTurtle (double d)
Definition at line 39 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by view.Workspace.addTurtle(), and model.instructions.MultipleTurtlesInstruction.execute().
void model.ExecutionEnvironment.addTurtleToActiveList (double turtle)
Definition at line 110 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by model.instructions.MultipleTurtlesInstruction.execute().
void model.ExecutionEnvironment.addVariable (String variableName, Double value)
Definition at line 48 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by view.SideBar.createVariableColumns(), model.instructions.UserRunningInstruction.execute(), and model.instructions.ControlInstruction.makeVariable().
void model.ExecutionEnvironment.clear ()
Definition at line 74 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.ExecutionEnvironment().
void model.ExecutionEnvironment.clearActiveList ()
Definition at line 105 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by model.instructions.MultipleTurtlesInstruction.execute().
Set<Integer> model.ExecutionEnvironment.getActiveList ()
Definition at line 101 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.activeTurtleList.
Referenced by model.Parser.parseAndExecute().
int model.ExecutionEnvironment.getActiveTurtle ()
Definition at line 84 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.activeTurtle.
Referenced by model.instructions.TurtleRequestInstruction.execute(), model.instructions.MultipleTurtlesInstruction.execute(), model.instructions.FrontEndInstruction.execute(), model.instructions.MovementInstruction.execute(), and model.instructions.MovementInstruction.updateView().
Instruction model.ExecutionEnvironment.getCommand (String key)
Definition at line 70 of file ExecutionEnvironment.java.
Referenced by model.instructions.UserRunningInstruction.execute().
Set<Integer> model.ExecutionEnvironment.getTurtles ()
Definition at line 44 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.myTurtleList.
Referenced by model.instructions.MultipleTurtlesInstruction.execute(), and model.instructions.MovementInstruction.execute().
Map<String, Instruction> model.ExecutionEnvironment.getUserCommandMap ()
Definition at line 93 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.myUserInstructionMap.
Referenced by model.Parser.makeTree(), and view.ViewUpdater.update().
Double model.ExecutionEnvironment.getVariable (String key)
Definition at line 61 of file ExecutionEnvironment.java.
Referenced by model.instructions.Variable.execute().
Map<String, Double> model.ExecutionEnvironment.getVariableMap ()
Definition at line 97 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.myVariableMap.
Referenced by view.ViewUpdater.update().
void model.ExecutionEnvironment.removeDuplicate (String s)
Definition at line 65 of file ExecutionEnvironment.java.
void model.ExecutionEnvironment.setActiveTurtle (double turtle)
Definition at line 88 of file ExecutionEnvironment.java.
References model.ExecutionEnvironment.updateObserver().
Referenced by view.Workspace.addTurtle(), model.instructions.MultipleTurtlesInstruction.execute(), and model.Parser.parseAndExecute().
void model.ExecutionEnvironment.updateObserver () private
Definition at line 55 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.addCommand(), model.ExecutionEnvironment.addTurtle(), model.ExecutionEnvironment.addTurtleToActiveList(), model.ExecutionEnvironment.addVariable(), model.ExecutionEnvironment.clearActiveList(), and model.ExecutionEnvironment.setActiveTurtle().
Member Data Documentation
int model.ExecutionEnvironment.activeTurtle private
Definition at line 26 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.getActiveTurtle().
Set<Integer> model.ExecutionEnvironment.activeTurtleList private
Definition at line 25 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.getActiveList().
Set<Integer> model.ExecutionEnvironment.myTurtleList private
Definition at line 24 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.getTurtles().
Map<String,Instruction> model.ExecutionEnvironment.myUserInstructionMap private
Definition at line 22 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.getUserCommandMap().
Map<String, Double> model.ExecutionEnvironment.myVariableMap private
Definition at line 23 of file ExecutionEnvironment.java.
Referenced by model.ExecutionEnvironment.getVariableMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/ExecutionEnvironment.java