slogo_team12: view.MainView Class Reference
view.MainView Class Reference
Public Member Functions
MainView (Stage s)
Private Member Functions
void initTabs (SLogoView sLogoView)
void initScreen ()
void initStage (Stage s)
void initRowConstraints (GridPane grid)
MenuBar configureTopMenu ()
Menu configureInfoMenu ()
Menu configureFileMenu ()
void newTab ()
void displayPage (String loc)
Private Attributes
Dimension2D myDimensions
ResourceBundle myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english")
Stage myStage
TabPane myTabPane = new TabPane()
SceneSetter mySceneSetter = new SceneSetter()
int myTabCount
Static Private Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
Detailed Description
Main view class containing the menupane and tabpane, which do not change regardless of the number of tabs/scenes added
Author
Callie, Mengchao
Definition at line 26 of file MainView.java.
Constructor & Destructor Documentation
view.MainView.MainView (Stage s)
Definition at line 36 of file MainView.java.
References view.MainView.initRowConstraints(), view.MainView.initScreen(), view.MainView.initStage(), view.MainView.initTabs(), view.MainView.myResources, and view.SceneSetter.setupScene().
Member Function Documentation
Menu view.MainView.configureFileMenu () private
Definition at line 93 of file MainView.java.
References view.MainView.newTab().
Referenced by view.MainView.configureTopMenu().
Menu view.MainView.configureInfoMenu () private
Definition at line 85 of file MainView.java.
References view.MainView.displayPage().
Referenced by view.MainView.configureTopMenu().
MenuBar view.MainView.configureTopMenu () private
Definition at line 77 of file MainView.java.
References view.MainView.configureFileMenu(), and view.MainView.configureInfoMenu().
Referenced by view.MainView.initRowConstraints().
void view.MainView.displayPage (String loc) private
Definition at line 114 of file MainView.java.
References view.SceneSetter.setupScene().
Referenced by view.MainView.configureInfoMenu().
void view.MainView.initRowConstraints (GridPane grid) private
Definition at line 66 of file MainView.java.
References view.MainView.configureTopMenu().
Referenced by view.MainView.MainView().
void view.MainView.initScreen () private
Definition at line 55 of file MainView.java.
Referenced by view.MainView.MainView().
void view.MainView.initStage (Stage s) private
Definition at line 61 of file MainView.java.
Referenced by view.MainView.MainView().
void view.MainView.initTabs (SLogoView sLogoView) private
Definition at line 48 of file MainView.java.
References view.SLogoView.configureUI().
Referenced by view.MainView.MainView().
void view.MainView.newTab () private
Definition at line 104 of file MainView.java.
References view.SLogoView.configureUI(), and view.MainView.myTabCount.
Referenced by view.MainView.configureFileMenu().
Member Data Documentation
final String view.MainView.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static private
Definition at line 29 of file MainView.java.
Dimension2D view.MainView.myDimensions private
Definition at line 28 of file MainView.java.
ResourceBundle view.MainView.myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english") private
Definition at line 30 of file MainView.java.
Referenced by view.MainView.MainView().
SceneSetter view.MainView.mySceneSetter = new SceneSetter() private
Definition at line 33 of file MainView.java.
Stage view.MainView.myStage private
Definition at line 31 of file MainView.java.
int view.MainView.myTabCount private
Definition at line 34 of file MainView.java.
Referenced by view.MainView.newTab().
TabPane view.MainView.myTabPane = new TabPane() private
Definition at line 32 of file MainView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/MainView.java