slogo_team12: view.SideBar Class Reference
view.SideBar Class Reference
Public Member Functions
SideBar ()
void setParser (Parser parser)
void updateVariable (Property variable)
void setHistory (String string)
void updateExecutionEnvironment (ExecutionEnvironment env)
void updateCommand (String newCommand)
Protected Member Functions
void updateTurtleProperties (int ID, Workspace workspace)
Private Member Functions
void setDimensionRestrictions ()
void createHistoryPane ()
void createUserCommandsPane ()
ListView< String > createListView (ObservableList< String > items, int height)
Private Attributes
ObservableList< String > myHistoryItems
ObservableList< Property > myVariablesList
Parser myParser
TableView< Property > myVariablesTable
TableView< Property > myTurtlePropertiesTable
ObservableList< String > myCommandItems
ExecutionEnvironment myEnvironment
ResourceBundle myResources
TurtlePropertiesView myTurtlePropertiesPane
VariablesView myVariablesPane
Static Private Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
static final String NAME_VARIABLE = "myName"
static final String PROPERTY_VARIABLE = "myProperty"
Detailed Description
Right sidebar containing display properties of a turle's history, commands header, variables, and properties. The user can interact with some of these modules and directly edit/change them
Author
Callie
Definition at line 33 of file SideBar.java.
Constructor & Destructor Documentation
view.SideBar.SideBar ()
Definition at line 52 of file SideBar.java.
References view.SideBar.createHistoryPane(), view.SideBar.createUserCommandsPane(), view.SideBar.myEnvironment, view.SideBar.NAME_VARIABLE, view.SideBar.PROPERTY_VARIABLE, and view.SideBar.setDimensionRestrictions().
Member Function Documentation
void view.SideBar.createHistoryPane () private
Definition at line 111 of file SideBar.java.
References view.SideBar.createListView(), and model.Parser.parseAndExecute().
Referenced by view.SideBar.SideBar().
ListView<String> view.SideBar.createListView (ObservableList< String > items, int height) private
Definition at line 134 of file SideBar.java.
Referenced by view.SideBar.createHistoryPane(), and view.SideBar.createUserCommandsPane().
void view.SideBar.createUserCommandsPane () private
Definition at line 128 of file SideBar.java.
References view.SideBar.createListView().
Referenced by view.SideBar.SideBar().
void view.SideBar.setDimensionRestrictions () private
Definition at line 80 of file SideBar.java.
Referenced by view.SideBar.SideBar().
void view.SideBar.setHistory (String string)
Definition at line 72 of file SideBar.java.
Referenced by view.Editor.parse().
void view.SideBar.setParser (Parser parser)
Definition at line 64 of file SideBar.java.
void view.SideBar.updateCommand (String newCommand)
Definition at line 101 of file SideBar.java.
Referenced by view.ViewUpdater.updateCommand().
void view.SideBar.updateExecutionEnvironment (ExecutionEnvironment env)
Definition at line 86 of file SideBar.java.
Referenced by view.ViewUpdater.update().
void view.SideBar.updateTurtleProperties (int ID, Workspace workspace) protected
Definition at line 76 of file SideBar.java.
References view.TurtlePropertiesView.update().
Referenced by view.ViewUpdater.clearScreen(), view.Drawer.draw(), view.Workspace.setActiveTurtle(), view.ViewUpdater.setHeading(), view.SLogoView.setHeading(), view.ViewUpdater.setPenUp(), view.SLogoView.setPenUp(), view.ViewUpdater.setXY(), view.SLogoView.setXY(), view.ViewUpdater.showTurtle(), and view.SLogoView.showTurtle().
void view.SideBar.updateVariable (Property variable)
Definition at line 68 of file SideBar.java.
References view.VariablesView.update().
Referenced by view.ViewUpdater.update(), and view.SLogoView.updateVariables().
Member Data Documentation
final String view.SideBar.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static private
Definition at line 43 of file SideBar.java.
ObservableList<String> view.SideBar.myCommandItems private
Definition at line 40 of file SideBar.java.
ExecutionEnvironment view.SideBar.myEnvironment private
Definition at line 41 of file SideBar.java.
Referenced by view.SideBar.SideBar().
ObservableList<String> view.SideBar.myHistoryItems private
Definition at line 35 of file SideBar.java.
Parser view.SideBar.myParser private
Definition at line 37 of file SideBar.java.
ResourceBundle view.SideBar.myResources private
Initial value:
= ResourceBundle
            .getBundle(DEFAULT_RESOURCE_PACKAGE + "english")
Definition at line 44 of file SideBar.java.
TurtlePropertiesView view.SideBar.myTurtlePropertiesPane private
Definition at line 49 of file SideBar.java.
TableView<Property> view.SideBar.myTurtlePropertiesTable private
Definition at line 39 of file SideBar.java.
ObservableList<Property> view.SideBar.myVariablesList private
Definition at line 36 of file SideBar.java.
VariablesView view.SideBar.myVariablesPane private
Definition at line 50 of file SideBar.java.
TableView<Property> view.SideBar.myVariablesTable private
Definition at line 38 of file SideBar.java.
final String view.SideBar.NAME_VARIABLE = "myName" static private
Definition at line 46 of file SideBar.java.
Referenced by view.SideBar.SideBar().
final String view.SideBar.PROPERTY_VARIABLE = "myProperty" static private
Definition at line 47 of file SideBar.java.
Referenced by view.SideBar.SideBar().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/SideBar.java