slogo_team12: model.instructions.ControlInstruction Class Reference
model.instructions.ControlInstruction Class Reference
Classes
enum implementers
Public Member Functions
ControlInstruction (List< Instruction > dependencies, String instructionType, ViewUpdater updater, ExecutionEnvironment environment)
double execute ()
double addToMap ()
double forLoop (Instruction varHead, Instruction listHead, int startIndex, int endIndex, int increment)
double executeList (Instruction listHead)
double makeVariable (Instruction input, Instruction value)
int getNumberOfArguments ()
Public Member Functions inherited from model.instructions.Instruction
Instruction (List< Instruction > dependencies, String instructionType, ViewUpdater updater, ExecutionEnvironment environment)
Instruction (String constantInput, ExecutionEnvironment environment)
abstract double execute ()
abstract int getNumberOfArguments ()
TurtleCommand getTurtleCommand ()
String getName ()
void update (Observable o, Object arg)
Additional Inherited Members
Protected Attributes inherited from model.instructions.Instruction
List< Instruction > myDependencies
String myInstructionType
ViewUpdater myViewUpdater
ExecutionEnvironment myEnvironment
Detailed Description
Control Instructions deal with program flow or variable creation. Since many of these commands use the same loop, a loop is available at the bottom. This class plays a small role in recursion.
Author
Greg, Sid
Definition at line 15 of file ControlInstruction.java.
Constructor & Destructor Documentation
model.instructions.ControlInstruction.ControlInstruction (List< Instruction > dependencies, String instructionType, ViewUpdater updater, ExecutionEnvironment environment)
Definition at line 17 of file ControlInstruction.java.
Member Function Documentation
double model.instructions.ControlInstruction.addToMap ()
Definition at line 76 of file ControlInstruction.java.
References model.ExecutionEnvironment.addCommand(), model.instructions.Instruction.myDependencies, and model.instructions.Instruction.myEnvironment.
Referenced by model.instructions.ControlInstruction.execute().
double model.instructions.ControlInstruction.execute ()
Definition at line 36 of file ControlInstruction.java.
References model.instructions.ControlInstruction.addToMap(), model.instructions.ControlInstruction.executeList(), model.instructions.ControlInstruction.forLoop(), model.instructions.ControlInstruction.makeVariable(), model.instructions.Instruction.myDependencies, model.instructions.Instruction.myEnvironment, and model.instructions.Instruction.myInstructionType.
double model.instructions.ControlInstruction.executeList (Instruction listHead)
Definition at line 92 of file ControlInstruction.java.
References model.instructions.Instruction.execute(), and model.instructions.Instruction.myDependencies.
Referenced by model.instructions.ControlInstruction.execute().
double model.instructions.ControlInstruction.forLoop (Instruction varHead, Instruction listHead, int startIndex, int endIndex, int increment)
Definition at line 81 of file ControlInstruction.java.
References model.instructions.Instruction.execute(), model.instructions.ControlInstruction.makeVariable(), model.instructions.Instruction.myDependencies, and model.instructions.Instruction.myEnvironment.
Referenced by model.instructions.ControlInstruction.execute().
int model.instructions.ControlInstruction.getNumberOfArguments ()
Definition at line 106 of file ControlInstruction.java.
References model.instructions.Instruction.myInstructionType.
double model.instructions.ControlInstruction.makeVariable (Instruction input, Instruction value)
Definition at line 100 of file ControlInstruction.java.
References model.ExecutionEnvironment.addVariable(), model.instructions.Instruction.execute(), model.instructions.Instruction.getName(), and model.instructions.Instruction.myEnvironment.
Referenced by model.instructions.ControlInstruction.execute(), and model.instructions.ControlInstruction.forLoop().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/instructions/ControlInstruction.java