slogo_team12: model.Parser Class Reference
model.Parser Class Reference
Public Member Functions
Parser (SLogoView view)
void parseAndExecute (String input)
void setLanguage (String language)
void update (Observable o, Object arg)
Private Member Functions
void addAllPatterns (String language)
void makePatterns (String resourceInput)
void makeCommandMap ()
Node makeTree (String[] command) throws ModelException
boolean match (String input, Pattern regex)
String testMatches (String test)
Private Attributes
List< Entry< String, Pattern > > myPatterns
Map< String, String > myCommandMap
int myFurthestDepth
SLogoView mySLogoView
ViewUpdater myViewUpdater
ExecutionEnvironment myExecutionParameters
Static Private Attributes
static final String[] COMMAND_TYPES = new String[]{"BooleanInstruction","ControlInstruction","FrontEndInstruction","MathInstruction","MovementInstruction","MultipleTurtlesInstruction","TurtleRequestInstruction"}
Detailed Description
This class is used as the primary backend class. The parser reads in a string value and creates an expression tree of instructions that can are then executed. Valid instructions are given in an enum at the head of each instruction file, and are read into the Command Types array. This class also handles enabing all other classes to observe the execution environment passed in to each instruction. Note, our list implementation does not allow a list to return a value
Author
Primary: Greg, Secondary: Sid
Definition at line 32 of file Parser.java.
Constructor & Destructor Documentation
model.Parser.Parser (SLogoView view)
Definition at line 42 of file Parser.java.
References model.Parser.addAllPatterns(), model.Parser.makeCommandMap(), and view.SLogoView.setEnvironment().
Member Function Documentation
void model.Parser.addAllPatterns (String language) private
Definition at line 55 of file Parser.java.
References model.Parser.makePatterns().
Referenced by model.Parser.Parser(), and model.Parser.setLanguage().
void model.Parser.makeCommandMap () private
Definition at line 70 of file Parser.java.
Referenced by model.Parser.Parser().
void model.Parser.makePatterns (String resourceInput) private
Definition at line 60 of file Parser.java.
Referenced by model.Parser.addAllPatterns().
Node model.Parser.makeTree (String[] command) throws ModelException private
Definition at line 111 of file Parser.java.
References model.Node.addChild(), model.ExecutionEnvironment.addCommand(), model.Node.getChildren(), model.Node.getInstruction(), model.instructions.Instruction.getNumberOfArguments(), model.ExecutionEnvironment.getUserCommandMap(), model.Parser.match(), model.Parser.myViewUpdater, view.SLogoView.openDialog(), and model.Parser.testMatches().
Referenced by model.Parser.parseAndExecute().
boolean model.Parser.match (String input, Pattern regex) private
Definition at line 200 of file Parser.java.
Referenced by model.Parser.makeTree(), and model.Parser.testMatches().
void model.Parser.parseAndExecute (String input)
Definition at line 86 of file Parser.java.
References model.ExecutionEnvironment.getActiveList(), model.Parser.makeTree(), view.SLogoView.openDialog(), and model.ExecutionEnvironment.setActiveTurtle().
Referenced by view.SideBar.createHistoryPane(), and view.Editor.parse().
void model.Parser.setLanguage (String language)
Definition at line 215 of file Parser.java.
References model.Parser.addAllPatterns().
Referenced by view.CustomizationBar.configureLanguageOptions().
String model.Parser.testMatches (String test) private
Definition at line 204 of file Parser.java.
References model.Parser.match().
Referenced by model.Parser.makeTree().
void model.Parser.update (Observable o, Object arg)
Definition at line 221 of file Parser.java.
Member Data Documentation
final String [] model.Parser.COMMAND_TYPES = new String[]{"BooleanInstruction","ControlInstruction","FrontEndInstruction","MathInstruction","MovementInstruction","MultipleTurtlesInstruction","TurtleRequestInstruction"} static private
Definition at line 36 of file Parser.java.
Map<String,String> model.Parser.myCommandMap private
Definition at line 35 of file Parser.java.
ExecutionEnvironment model.Parser.myExecutionParameters private
Definition at line 40 of file Parser.java.
int model.Parser.myFurthestDepth private
Definition at line 37 of file Parser.java.
List<Entry<String, Pattern> > model.Parser.myPatterns private
Definition at line 34 of file Parser.java.
SLogoView model.Parser.mySLogoView private
Definition at line 38 of file Parser.java.
ViewUpdater model.Parser.myViewUpdater private
Definition at line 39 of file Parser.java.
Referenced by model.Parser.makeTree().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/Parser.java