slogo_team12: model.XMLParser Class Reference
model.XMLParser Class Reference
Public Member Functions
XMLParser (File XMLFile)
Static Public Member Functions
static void clean (Node node)
Private Member Functions
void readFile (Document doc)
void readVariables (NodeList variableChildren)
void readInstructions (NodeList instructionChildren)
NodeList initializeNodeList (Document doc, String element)
Document initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException
Private Attributes
Map< String, Double > myVariableMap = new HashMap<String, Double>()
List< XMLInstruction > myUserInstructions = new ArrayList<XMLInstruction>()
Detailed Description
A functioning XMLParser This is based heavily off of the parser I made for the CellSociety project It has been improved to deal with the deeper levels of nodes that our XMLFile would require This has not been connected to the rest of the program due to a lack of time Theoretically, this could load in user variables and instructions that had been previously saved
Author
Sid
Definition at line 30 of file XMLParser.java.
Constructor & Destructor Documentation
model.XMLParser.XMLParser (File XMLFile)
Definition at line 35 of file XMLParser.java.
References model.XMLParser.clean(), model.XMLParser.initializeDoc(), and model.XMLParser.readFile().
Member Function Documentation
static void model.XMLParser.clean (Node node) static
Method that cleans white space and stray characters out of XML file Taken from: http://stackoverflow.com/questions/978810/how-to-strip-whitespace-only -text-nodes-from-a-dom-before-serialization/16285664#16285664
Parameters
node
Definition at line 83 of file XMLParser.java.
Referenced by model.XMLParser.XMLParser().
Document model.XMLParser.initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException private
Does initial set-up of document file.
Definition at line 118 of file XMLParser.java.
Referenced by model.XMLParser.XMLParser().
NodeList model.XMLParser.initializeNodeList (Document doc, String element) private
Function to do initial set-up Returns a node list of all elements of one type Ex. returns list of parameters or list of grid rows
Definition at line 107 of file XMLParser.java.
Referenced by model.XMLParser.readFile().
void model.XMLParser.readFile (Document doc) private
Definition at line 47 of file XMLParser.java.
References model.XMLParser.initializeNodeList(), model.XMLParser.readInstructions(), and model.XMLParser.readVariables().
Referenced by model.XMLParser.XMLParser().
void model.XMLParser.readInstructions (NodeList instructionChildren) private
Definition at line 62 of file XMLParser.java.
Referenced by model.XMLParser.readFile().
void model.XMLParser.readVariables (NodeList variableChildren) private
Definition at line 54 of file XMLParser.java.
Referenced by model.XMLParser.readFile().
Member Data Documentation
List<XMLInstruction> model.XMLParser.myUserInstructions = new ArrayList<XMLInstruction>() private
Definition at line 33 of file XMLParser.java.
Map<String, Double> model.XMLParser.myVariableMap = new HashMap<String, Double>() private
Definition at line 32 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/XMLParser.java