slogo_team12: view.TurtlePropertiesView Class Reference
view.TurtlePropertiesView Class Reference
Public Member Functions
TurtlePropertiesView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal)
Public Member Functions inherited from view.SideTableView
SideTableView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal)
TableColumn< Property, String > getLeftTableCol ()
TableColumn< Property, String > getRightTableCol ()
TableView< Property > getTable ()
Public Member Functions inherited from view.SidePropertiesView
SidePropertiesView (String s, ObservableList< Node > children)
Static Public Attributes
static final String IDValue = "ID"
static final String XPos = "X-Position"
static final String YPos = "Y-Position"
static final String Heading = "Heading"
static final String PenPos = "Pen Position"
static final String TurImg = "Turtle Image"
Protected Member Functions
void update (int ID, Workspace workspace)
Protected Member Functions inherited from view.SideTableView
void createView ()
void createColumns ()
Protected Member Functions inherited from view.SidePropertiesView
ObservableList< Node > getChildren ()
abstract void createView ()
Additional Inherited Members
Package Attributes inherited from view.SideTableView
TableColumn< Property, String > leftTableCol
TableColumn< Property, String > rightTableCol
Detailed Description
Definition at line 18 of file TurtlePropertiesView.java.
Constructor & Destructor Documentation
view.TurtlePropertiesView.TurtlePropertiesView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal)
Definition at line 27 of file TurtlePropertiesView.java.
Member Function Documentation
void view.TurtlePropertiesView.update (int ID, Workspace workspace) protected
Definition at line 32 of file TurtlePropertiesView.java.
References view.TurtleView.getHeading(), view.TurtleView.getID(), view.SideTableView.getTable(), view.Workspace.getTurtleMap(), and view.TurtleView.getYCoord().
Referenced by view.SideBar.updateTurtleProperties().
Member Data Documentation
final String view.TurtlePropertiesView.Heading = "Heading" static
Definition at line 23 of file TurtlePropertiesView.java.
final String view.TurtlePropertiesView.IDValue = "ID" static
Definition at line 20 of file TurtlePropertiesView.java.
final String view.TurtlePropertiesView.PenPos = "Pen Position" static
Definition at line 24 of file TurtlePropertiesView.java.
final String view.TurtlePropertiesView.TurImg = "Turtle Image" static
Definition at line 25 of file TurtlePropertiesView.java.
final String view.TurtlePropertiesView.XPos = "X-Position" static
Definition at line 21 of file TurtlePropertiesView.java.
final String view.TurtlePropertiesView.YPos = "Y-Position" static
Definition at line 22 of file TurtlePropertiesView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/TurtlePropertiesView.java