slogo_team12: view.CustomizationBar Class Reference
view.CustomizationBar Class Reference
Public Member Functions
CustomizationBar (Map< Integer, TurtleView > turtleList, Drawer drawer, Workspace workspace, Stage stage, Dimension2D dimensions)
void setParser (Parser parser)
Private Member Functions
void selectBackgroundColor (Dimension2D dimensions)
void selectPenColor (Drawer drawer)
void uploadTurtleFile (TurtleView turtle)
File displayFileChooser ()
void changeTurtleImage (TurtleView turtle, Image img)
void changeBackgroundColor (Color color)
HBox configureLanguageOptions ()
void selectTurtleImage (Dimension2D dimensions)
Private Attributes
Parser myParser
Workspace myWorkspace
Stage myStage
ResourceBundle myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english")
Static Private Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
Detailed Description
Customization for the bar at the top that allows the user to set the visual representations of the IDE
Author
Callie
Definition at line 31 of file CustomizationBar.java.
Constructor & Destructor Documentation
view.CustomizationBar.CustomizationBar (Map< Integer, TurtleView > turtleList, Drawer drawer, Workspace workspace, Stage stage, Dimension2D dimensions)
Definition at line 39 of file CustomizationBar.java.
References view.CustomizationBar.configureLanguageOptions(), view.CustomizationBar.selectBackgroundColor(), view.CustomizationBar.selectPenColor(), and view.CustomizationBar.selectTurtleImage().
Member Function Documentation
void view.CustomizationBar.changeBackgroundColor (Color color) private
Definition at line 98 of file CustomizationBar.java.
References view.Workspace.setBackground().
Referenced by view.CustomizationBar.selectBackgroundColor().
void view.CustomizationBar.changeTurtleImage (TurtleView turtle, Image img) private
Definition at line 94 of file CustomizationBar.java.
Referenced by view.CustomizationBar.uploadTurtleFile().
HBox view.CustomizationBar.configureLanguageOptions () private
Definition at line 102 of file CustomizationBar.java.
References model.Parser.setLanguage().
Referenced by view.CustomizationBar.CustomizationBar().
File view.CustomizationBar.displayFileChooser () private
Definition at line 85 of file CustomizationBar.java.
Referenced by view.CustomizationBar.uploadTurtleFile().
void view.CustomizationBar.selectBackgroundColor (Dimension2D dimensions) private
Definition at line 58 of file CustomizationBar.java.
References view.CustomizationBar.changeBackgroundColor().
Referenced by view.CustomizationBar.CustomizationBar().
void view.CustomizationBar.selectPenColor (Drawer drawer) private
Definition at line 71 of file CustomizationBar.java.
References view.Drawer.changeColor().
Referenced by view.CustomizationBar.CustomizationBar().
void view.CustomizationBar.selectTurtleImage (Dimension2D dimensions) private
Definition at line 123 of file CustomizationBar.java.
References view.Workspace.getActiveTurtle(), and view.CustomizationBar.uploadTurtleFile().
Referenced by view.CustomizationBar.CustomizationBar().
void view.CustomizationBar.setParser (Parser parser)
Definition at line 54 of file CustomizationBar.java.
Referenced by view.SLogoView.configureUI().
void view.CustomizationBar.uploadTurtleFile (TurtleView turtle) private
Definition at line 80 of file CustomizationBar.java.
References view.CustomizationBar.changeTurtleImage(), and view.CustomizationBar.displayFileChooser().
Referenced by view.CustomizationBar.selectTurtleImage().
Member Data Documentation
final String view.CustomizationBar.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static private
Definition at line 36 of file CustomizationBar.java.
Parser view.CustomizationBar.myParser private
Definition at line 33 of file CustomizationBar.java.
ResourceBundle view.CustomizationBar.myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english") private
Definition at line 37 of file CustomizationBar.java.
Stage view.CustomizationBar.myStage private
Definition at line 35 of file CustomizationBar.java.
Workspace view.CustomizationBar.myWorkspace private
Definition at line 34 of file CustomizationBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/CustomizationBar.java