slogo_team12: view.SidePropertiesView Class Reference
view.SidePropertiesView Class Reference abstract
Public Member Functions
SidePropertiesView (String s, ObservableList< Node > children)
Protected Member Functions
ObservableList< Node > getChildren ()
abstract void createView ()
Private Member Functions
void createTitleText (String s)
Private Attributes
ObservableList< Node > myChildren
Detailed Description
Definition at line 11 of file SidePropertiesView.java.
Constructor & Destructor Documentation
view.SidePropertiesView.SidePropertiesView (String s, ObservableList< Node > children)
Definition at line 15 of file SidePropertiesView.java.
References view.SidePropertiesView.createTitleText(), and view.SidePropertiesView.createView().
Member Function Documentation
void view.SidePropertiesView.createTitleText (String s) private
Definition at line 21 of file SidePropertiesView.java.
Referenced by view.SidePropertiesView.SidePropertiesView().
abstract void view.SidePropertiesView.createView () abstract protected
Referenced by view.SidePropertiesView.SidePropertiesView().
ObservableList<Node> view.SidePropertiesView.getChildren () protected
Definition at line 28 of file SidePropertiesView.java.
References view.SidePropertiesView.myChildren.
Referenced by view.SideTableView.createView().
Member Data Documentation
ObservableList<Node> view.SidePropertiesView.myChildren private
Definition at line 13 of file SidePropertiesView.java.
Referenced by view.SidePropertiesView.getChildren().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/SidePropertiesView.java