slogo_team12: view.Drawer Class Reference
view.Drawer Class Reference
Public Member Functions
Drawer (Workspace workspace)
void setStroke (Double size)
List< Polyline > draw (Map< Integer, TurtleView > turtles, List< TurtleCommand > instructions, SideBar sidebar)
void changeColor (Color c)
Private Member Functions
void wrapY (int dir, TurtleView turtle, Polar polar, List< Polyline > lines, int i, double newY, double startX, double moveX, double moveY, double turtleY, double startY)
void wrapX (int dir, TurtleView turtle, Polar polar, List< Polyline > lines, int i, double newX, double startY, double moveY, double moveX, double turtleX, double startX)
Polyline drawLine (double startX, double startY, double endX, double endY)
Private Attributes
Color myColor
double[] myXBounds = new double[2]
double[] myYBounds = new double[2]
double[] myHalf = new double[2]
Workspace myWorkspace
double strokeSize
int myIndex
Detailed Description
Draws and animates the lines following movement of a turtle
Author
Mengchao, Callie
Definition at line 19 of file Drawer.java.
Constructor & Destructor Documentation
view.Drawer.Drawer (Workspace workspace)
Definition at line 29 of file Drawer.java.
References view.Workspace.getGridHeight(), and view.Workspace.getGridWidth().
Member Function Documentation
void view.Drawer.changeColor (Color c)
Definition at line 200 of file Drawer.java.
Referenced by view.CustomizationBar.selectPenColor(), and view.ViewUpdater.setPenColor().
List<Polyline> view.Drawer.draw (Map< Integer, TurtleView > turtles, List< TurtleCommand > instructions, SideBar sidebar)
Definition at line 49 of file Drawer.java.
References model.Polar.getAngle(), model.Polar.getDistance(), view.TurtleView.getPenUp(), model.TurtleCommand.getPolar(), model.TurtleCommand.getTurtleId(), model.TurtleCommand.isRelative(), view.TurtleView.move(), view.Drawer.myWorkspace, view.TurtleView.setAbsoluteHeading(), view.TurtleView.setRelativeHeading(), view.SideBar.updateTurtleProperties(), view.Drawer.wrapX(), and view.Drawer.wrapY().
Referenced by view.ViewUpdater.updateWorkspace().
Polyline view.Drawer.drawLine (double startX, double startY, double endX, double endY) private
Definition at line 188 of file Drawer.java.
Referenced by view.Drawer.wrapX(), and view.Drawer.wrapY().
void view.Drawer.setStroke (Double size)
Definition at line 43 of file Drawer.java.
Referenced by view.ViewUpdater.setPenSize().
void view.Drawer.wrapX (int dir, TurtleView turtle, Polar polar, List< Polyline > lines, int i, double newX, double startY, double moveY, double moveX, double turtleX, double startX) private
Definition at line 173 of file Drawer.java.
References view.Drawer.drawLine(), view.TurtleView.getPenUp(), and view.TurtleView.move().
Referenced by view.Drawer.draw().
void view.Drawer.wrapY (int dir, TurtleView turtle, Polar polar, List< Polyline > lines, int i, double newY, double startX, double moveX, double moveY, double turtleY, double startY) private
Definition at line 154 of file Drawer.java.
References view.Drawer.drawLine(), view.TurtleView.getPenUp(), and view.TurtleView.move().
Referenced by view.Drawer.draw().
Member Data Documentation
Color view.Drawer.myColor private
Definition at line 21 of file Drawer.java.
double [] view.Drawer.myHalf = new double[2] private
Definition at line 24 of file Drawer.java.
int view.Drawer.myIndex private
Definition at line 27 of file Drawer.java.
Workspace view.Drawer.myWorkspace private
Definition at line 25 of file Drawer.java.
Referenced by view.Drawer.draw().
double [] view.Drawer.myXBounds = new double[2] private
Definition at line 22 of file Drawer.java.
double [] view.Drawer.myYBounds = new double[2] private
Definition at line 23 of file Drawer.java.
double view.Drawer.strokeSize private
Definition at line 26 of file Drawer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/Drawer.java