slogo_team12: view.Workspace Class Reference
view.Workspace Class Reference
Public Member Functions
Workspace (Dimension2D dimensions, SideBar sidebar)
void addTurtle (ExecutionEnvironment update)
void setBackground (Color color)
double getGridWidth ()
double getGridHeight ()
void setActiveTurtle (int ID)
Map< Integer, TurtleView > getTurtleMap ()
Group getLines ()
void clearLines ()
TurtleView getActiveTurtle ()
Private Member Functions
void configureTurtleEventHandler (int ID)
Private Attributes
Rectangle myBackground
Map< Integer, TurtleView > myTurtles
SideBar mySidebar
Group myLines
ResourceBundle myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english")
TurtleView myActiveTurtle
Static Private Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
static final int INITIAL_TURTLE_ID = 1
Detailed Description
Workspace for displaying turtles, lines, and the pane that displays the visual representation of the SLogo language.
Author
Callie
Definition at line 22 of file Workspace.java.
Constructor & Destructor Documentation
view.Workspace.Workspace (Dimension2D dimensions, SideBar sidebar)
Definition at line 33 of file Workspace.java.
References view.Workspace.addTurtle(), and view.Workspace.setActiveTurtle().
Member Function Documentation
void view.Workspace.addTurtle (ExecutionEnvironment update)
Definition at line 53 of file Workspace.java.
References model.ExecutionEnvironment.addTurtle(), view.Workspace.configureTurtleEventHandler(), and model.ExecutionEnvironment.setActiveTurtle().
Referenced by view.SLogoView.configureAddTurtlesButton(), and view.Workspace.Workspace().
void view.Workspace.clearLines ()
Definition at line 99 of file Workspace.java.
Referenced by view.ViewUpdater.clearScreen().
void view.Workspace.configureTurtleEventHandler (int ID) private
Definition at line 86 of file Workspace.java.
References view.TurtleView.getID(), and view.Workspace.setActiveTurtle().
Referenced by view.Workspace.addTurtle().
TurtleView view.Workspace.getActiveTurtle ()
Definition at line 103 of file Workspace.java.
References view.Workspace.myActiveTurtle.
Referenced by view.CustomizationBar.selectTurtleImage(), and view.ViewUpdater.setShape().
double view.Workspace.getGridHeight ()
Definition at line 77 of file Workspace.java.
Referenced by view.Drawer.Drawer().
double view.Workspace.getGridWidth ()
Definition at line 73 of file Workspace.java.
Referenced by view.Drawer.Drawer().
Group view.Workspace.getLines ()
Definition at line 95 of file Workspace.java.
References view.Workspace.myLines.
Referenced by view.ViewUpdater.updateWorkspace().
Map<Integer, TurtleView> view.Workspace.getTurtleMap ()
Definition at line 91 of file Workspace.java.
References view.Workspace.myTurtles.
Referenced by view.ViewUpdater.clearScreen(), view.ViewUpdater.clearStamps(), view.ViewUpdater.createStamp(), view.ViewUpdater.getHeading(), view.SLogoView.getHeading(), view.ViewUpdater.getPenDown(), view.SLogoView.getPenDown(), view.ViewUpdater.getShapeIndex(), view.ViewUpdater.getXCor(), view.SLogoView.getXCor(), view.ViewUpdater.getYCor(), view.SLogoView.getYCor(), view.ViewUpdater.isShowing(), view.SLogoView.isShowing(), view.ViewUpdater.setHeading(), view.SLogoView.setHeading(), view.ViewUpdater.setPenUp(), view.SLogoView.setPenUp(), view.ViewUpdater.setShape(), view.ViewUpdater.setXY(), view.SLogoView.setXY(), view.ViewUpdater.showTurtle(), view.SLogoView.showTurtle(), view.SideBar.updateTurtleProperties(), and view.ViewUpdater.updateWorkspace().
void view.Workspace.setActiveTurtle (int ID)
Definition at line 81 of file Workspace.java.
References view.SideBar.updateTurtleProperties().
Referenced by view.Workspace.configureTurtleEventHandler(), and view.Workspace.Workspace().
void view.Workspace.setBackground (Color color)
Definition at line 69 of file Workspace.java.
Referenced by view.CustomizationBar.changeBackgroundColor(), and view.ViewUpdater.setBackgroundColor().
Member Data Documentation
final String view.Workspace.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static private
Definition at line 28 of file Workspace.java.
final int view.Workspace.INITIAL_TURTLE_ID = 1 static private
Definition at line 31 of file Workspace.java.
TurtleView view.Workspace.myActiveTurtle private
Definition at line 30 of file Workspace.java.
Referenced by view.Workspace.getActiveTurtle().
Rectangle view.Workspace.myBackground private
Definition at line 24 of file Workspace.java.
Group view.Workspace.myLines private
Definition at line 27 of file Workspace.java.
Referenced by view.Workspace.getLines().
ResourceBundle view.Workspace.myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english") private
Definition at line 29 of file Workspace.java.
SideBar view.Workspace.mySidebar private
Definition at line 26 of file Workspace.java.
Map<Integer, TurtleView> view.Workspace.myTurtles private
Definition at line 25 of file Workspace.java.
Referenced by view.Workspace.getTurtleMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/Workspace.java