slogo_team12: view.TurtleView Class Reference
view.TurtleView Class Reference
Public Member Functions
TurtleView (int id, Image img)
void move (double moveX, double moveY)
double setXY (double x, double y)
double setRelativeHeading (double angle)
double setAbsoluteHeading (double angle)
void setPenUp (boolean isUp)
double getHeading ()
boolean getPenUp ()
String getPenPosition ()
String isShowing ()
void showTurtle (boolean show)
String getYCoord ()
int getID ()
void setImageID (int id)
int getImageID ()
int createStamp (Workspace workspace)
int clearStamps (Workspace workspace)
Private Member Functions
double adjustAngle (double angle)
Private Attributes
double myHeading
boolean penUp = false
int myID
int myImageID
Group myStamps
Detailed Description
Represents a turtle ImageView object that carries the properties and functionality of a turtle
Author
Callie, Mengchao
Definition at line 14 of file TurtleView.java.
Constructor & Destructor Documentation
view.TurtleView.TurtleView (int id, Image img)
Definition at line 22 of file TurtleView.java.
Member Function Documentation
double view.TurtleView.adjustAngle (double angle) private
Normalizes a double parameter to an angle between 0-360
Parameters
angle
Returns
normalized angle between 0-360
Definition at line 106 of file TurtleView.java.
Referenced by view.TurtleView.setAbsoluteHeading(), and view.TurtleView.setRelativeHeading().
int view.TurtleView.clearStamps (Workspace workspace)
Definition at line 137 of file TurtleView.java.
Referenced by view.ViewUpdater.clearStamps().
int view.TurtleView.createStamp (Workspace workspace)
Definition at line 126 of file TurtleView.java.
References view.TurtleView.getImageID(), and view.TurtleView.getYCoord().
Referenced by view.ViewUpdater.createStamp().
double view.TurtleView.getHeading ()
Definition at line 66 of file TurtleView.java.
References view.TurtleView.myHeading.
Referenced by view.TurtlePropertiesView.update().
int view.TurtleView.getID ()
Definition at line 114 of file TurtleView.java.
References view.TurtleView.myID.
Referenced by view.Workspace.configureTurtleEventHandler(), and view.TurtlePropertiesView.update().
int view.TurtleView.getImageID ()
Definition at line 122 of file TurtleView.java.
References view.TurtleView.myImageID.
Referenced by view.TurtleView.createStamp().
String view.TurtleView.getPenPosition ()
Definition at line 74 of file TurtleView.java.
boolean view.TurtleView.getPenUp ()
Definition at line 70 of file TurtleView.java.
References view.TurtleView.penUp.
Referenced by view.Drawer.draw(), view.Drawer.wrapX(), and view.Drawer.wrapY().
String view.TurtleView.getYCoord ()
Definition at line 92 of file TurtleView.java.
Referenced by view.TurtleView.createStamp(), and view.TurtlePropertiesView.update().
String view.TurtleView.isShowing ()
Definition at line 81 of file TurtleView.java.
void view.TurtleView.move (double moveX, double moveY)
Definition at line 35 of file TurtleView.java.
Referenced by view.Drawer.draw(), view.Drawer.wrapX(), and view.Drawer.wrapY().
double view.TurtleView.setAbsoluteHeading (double angle)
Definition at line 55 of file TurtleView.java.
References view.TurtleView.adjustAngle().
Referenced by view.Drawer.draw().
void view.TurtleView.setImageID (int id)
Definition at line 118 of file TurtleView.java.
void view.TurtleView.setPenUp (boolean isUp)
Definition at line 62 of file TurtleView.java.
double view.TurtleView.setRelativeHeading (double angle)
Definition at line 49 of file TurtleView.java.
References view.TurtleView.adjustAngle(), and view.TurtleView.myHeading.
Referenced by view.Drawer.draw().
double view.TurtleView.setXY (double x, double y)
Definition at line 41 of file TurtleView.java.
void view.TurtleView.showTurtle (boolean show)
Definition at line 88 of file TurtleView.java.
Member Data Documentation
double view.TurtleView.myHeading private
Definition at line 16 of file TurtleView.java.
Referenced by view.TurtleView.getHeading(), and view.TurtleView.setRelativeHeading().
int view.TurtleView.myID private
Definition at line 18 of file TurtleView.java.
Referenced by view.TurtleView.getID().
int view.TurtleView.myImageID private
Definition at line 19 of file TurtleView.java.
Referenced by view.TurtleView.getImageID().
Group view.TurtleView.myStamps private
Definition at line 20 of file TurtleView.java.
boolean view.TurtleView.penUp = false private
Definition at line 17 of file TurtleView.java.
Referenced by view.TurtleView.getPenUp().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/TurtleView.java