slogo_team12: view.VariablesView Class Reference
view.VariablesView Class Reference
Public Member Functions
VariablesView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal, ExecutionEnvironment env)
Public Member Functions inherited from view.SideTableView
SideTableView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal)
TableColumn< Property, String > getLeftTableCol ()
TableColumn< Property, String > getRightTableCol ()
TableView< Property > getTable ()
Public Member Functions inherited from view.SidePropertiesView
SidePropertiesView (String s, ObservableList< Node > children)
Protected Member Functions
void createColumns ()
void update (Property variable)
Protected Member Functions inherited from view.SideTableView
void createView ()
void createColumns ()
Protected Member Functions inherited from view.SidePropertiesView
ObservableList< Node > getChildren ()
abstract void createView ()
Package Attributes
ExecutionEnvironment myEnvironment
Package Attributes inherited from view.SideTableView
TableColumn< Property, String > leftTableCol
TableColumn< Property, String > rightTableCol
Private Attributes
ObservableList< Property > myVariablesList
Detailed Description
Definition at line 15 of file VariablesView.java.
Constructor & Destructor Documentation
view.VariablesView.VariablesView (String s, ObservableList< Node > children, String leftCol, String rightCol, String leftVal, String rightVal, ExecutionEnvironment env)
Definition at line 21 of file VariablesView.java.
References view.SideTableView.getTable().
Member Function Documentation
void view.VariablesView.createColumns () protected
Definition at line 30 of file VariablesView.java.
References model.ExecutionEnvironment.addVariable(), view.SideTableView.getLeftTableCol(), view.Property.getName(), view.SideTableView.getRightTableCol(), view.SideTableView.getTable(), and view.Property.setValue().
void view.VariablesView.update (Property variable) protected
Definition at line 46 of file VariablesView.java.
References view.Property.getName(), view.SideTableView.getTable(), and view.Property.getValue().
Referenced by view.SideBar.updateVariable().
Member Data Documentation
ExecutionEnvironment view.VariablesView.myEnvironment package
Definition at line 17 of file VariablesView.java.
ObservableList<Property> view.VariablesView.myVariablesList private
Definition at line 18 of file VariablesView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/VariablesView.java