slogo_team12: view.Property Class Reference
view.Property Class Reference
Public Member Functions
Property (String varName, double varValue)
Property (String varName, String property)
void setName (String name)
String getName ()
String getProperty ()
void setValue (double value)
double getValue ()
double getVar ()
StringProperty myNameProperty ()
DoubleProperty myVarProperty ()
StringProperty myPropertyProperty ()
Private Attributes
StringProperty myName
DoubleProperty myVar
StringProperty myProperty
Detailed Description
Display and value properties for an object that can be displayed in a visual TableView.
Author
Callie
Definition at line 13 of file Property.java.
Constructor & Destructor Documentation
view.Property.Property (String varName, double varValue)
Definition at line 19 of file Property.java.
view.Property.Property (String varName, String property)
Definition at line 24 of file Property.java.
Member Function Documentation
String view.Property.getName ()
Definition at line 33 of file Property.java.
Referenced by view.SideBar.createVariableColumns(), and view.SideBar.updateVariable().
String view.Property.getProperty ()
Definition at line 38 of file Property.java.
double view.Property.getValue ()
Definition at line 46 of file Property.java.
Referenced by view.SideBar.updateVariable().
double view.Property.getVar ()
Definition at line 50 of file Property.java.
StringProperty view.Property.myNameProperty ()
Definition at line 54 of file Property.java.
References view.Property.myName.
StringProperty view.Property.myPropertyProperty ()
Definition at line 62 of file Property.java.
References view.Property.myProperty.
DoubleProperty view.Property.myVarProperty ()
Definition at line 58 of file Property.java.
References view.Property.myVar.
void view.Property.setName (String name)
Definition at line 29 of file Property.java.
void view.Property.setValue (double value)
Definition at line 42 of file Property.java.
Referenced by view.SideBar.createVariableColumns().
Member Data Documentation
StringProperty view.Property.myName private
Definition at line 15 of file Property.java.
Referenced by view.Property.myNameProperty().
StringProperty view.Property.myProperty private
Definition at line 17 of file Property.java.
Referenced by view.Property.myPropertyProperty().
DoubleProperty view.Property.myVar private
Definition at line 16 of file Property.java.
Referenced by view.Property.myVarProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/Property.java